name: allvalue_link_demo
description: Demo Flutter NFC reader for AllValue Link
publish_to: none
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_nfc_kit: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


